import { formatToolBarcode } from "@/features/inventory/lib/barcode";
import type { AppBackup } from "@/core/db/schema";
import { BACKUP_SCHEMA_VERSION } from "@/core/db/schema";

function daysAgo(days: number) {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export function buildDevSeedBackup(): AppBackup {
  return {
    schemaVersion: BACKUP_SCHEMA_VERSION,
    exportedAt: new Date().toISOString(),
    origin: null,
    data: {
      tools: [
        {
          id: 1,
          barcode: formatToolBarcode(1),
          name: "Digital Microscope",
          description: "Portable digital microscope for lab viewing.",
          category: "Microscopy",
          currentStatus: "available",
          createdAt: daysAgo(20),
          updatedAt: daysAgo(2),
          deletedAt: null,
        },
        {
          id: 2,
          barcode: formatToolBarcode(2),
          name: "Soldering Station",
          description: "Temperature-controlled station for electronics work.",
          category: "Electronics",
          currentStatus: "borrowed",
          createdAt: daysAgo(18),
          updatedAt: daysAgo(1),
          deletedAt: null,
        },
        {
          id: 3,
          barcode: formatToolBarcode(3),
          name: "Oscilloscope",
          description: "Bench oscilloscope for waveform diagnostics.",
          category: "Electronics",
          currentStatus: "available",
          createdAt: daysAgo(15),
          updatedAt: daysAgo(4),
          deletedAt: null,
        },
        {
          id: 4,
          barcode: formatToolBarcode(4),
          name: "Pipette Set",
          description: "Adjustable pipette kit with case.",
          category: "Biology",
          currentStatus: "available",
          createdAt: daysAgo(12),
          updatedAt: daysAgo(3),
          deletedAt: null,
        },
      ],
      borrowers: [
        {
          id: "student-1",
          schoolId: "2024-0001",
          name: "Alyssa Ramos",
          email: null,
          image: null,
          type: "student",
          program: "BS Biology",
          yearLevel: 3,
          section: "B",
          contactNumber: "09171234567",
          createdAt: daysAgo(19),
          deletedAt: null,
        },
        {
          id: "student-2",
          schoolId: "2024-0002",
          name: "Marco Villanueva",
          email: null,
          image: null,
          type: "student",
          program: "BS Electronics",
          yearLevel: 4,
          section: "A",
          contactNumber: "09179876543",
          createdAt: daysAgo(17),
          deletedAt: null,
        },
        {
          id: "staff-1",
          schoolId: "STAFF-014",
          name: "Engr. Denise Cruz",
          email: null,
          image: null,
          type: "staff",
          program: null,
          yearLevel: null,
          section: null,
          contactNumber: "09170001122",
          createdAt: daysAgo(16),
          deletedAt: null,
        },
      ],
      transactions: [
        {
          id: 1,
          toolId: 2,
          barcode: formatToolBarcode(2),
          toolName: "Soldering Station",
          borrowerId: "student-2",
          borrowerSchoolId: "2024-0002",
          borrowerName: "Marco Villanueva",
          transactionType: "borrowed",
          recordedAt: daysAgo(1),
          notes: null,
        },
        {
          id: 2,
          toolId: 1,
          barcode: formatToolBarcode(1),
          toolName: "Digital Microscope",
          borrowerId: "student-1",
          borrowerSchoolId: "2024-0001",
          borrowerName: "Alyssa Ramos",
          transactionType: "borrowed",
          recordedAt: daysAgo(8),
          notes: null,
        },
        {
          id: 3,
          toolId: 1,
          barcode: formatToolBarcode(1),
          toolName: "Digital Microscope",
          borrowerId: "student-1",
          borrowerSchoolId: "2024-0001",
          borrowerName: "Alyssa Ramos",
          transactionType: "returned",
          recordedAt: daysAgo(6),
          notes: null,
        },
        {
          id: 4,
          toolId: 3,
          barcode: formatToolBarcode(3),
          toolName: "Oscilloscope",
          borrowerId: "staff-1",
          borrowerSchoolId: "STAFF-014",
          borrowerName: "Engr. Denise Cruz",
          transactionType: "borrowed",
          recordedAt: daysAgo(5),
          notes: null,
        },
        {
          id: 5,
          toolId: 3,
          barcode: formatToolBarcode(3),
          toolName: "Oscilloscope",
          borrowerId: "staff-1",
          borrowerSchoolId: "STAFF-014",
          borrowerName: "Engr. Denise Cruz",
          transactionType: "returned",
          recordedAt: daysAgo(4),
          notes: null,
        },
      ],
      appSettings: [
        {
          key: "seededAt",
          value: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      ],
    },
  };
}
